#!/bin/bash

MESSAGE=$(cat $1) 
TICKET=$(git rev-parse --abbrev-ref HEAD | grep -Eo '(\w+[-])?[0-9]+' | tr "[:lower:]" "[:upper:]")

if [[ "$MESSAGE" == *"$TICKET"* ]]; then
  echo "Ticket found in commit message." 
  exit 0
else
  echo "Don't worry champ!!!"
  echo "We 've got your back."
  echo "Adding ticket..."
fi

echo "[$TICKET] $MESSAGE" > $1
