#!/bin/sh

BRANCH=$(git rev-parse --abbrev-ref HEAD)
REGEX="^(develop|master|release|((feature|feature-set|task|bugfix|hotfix)\/[A-Z]+-[0-9]+\/.+))$"

if ! [[ $BRANCH =~ $REGEX ]]; then
  echo "Your commit was rejected due to branching name"
  echo "Please rename your branch with one of below syntax
  - develop
  - master
  - release
  - feature/...
  - feature-set/...
  - task/...
  - bugfix/...
  - hotfix/...
"
  exit 1
fi
